<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <RootNamespace>AdmissionAssistant.Core</RootNamespace>
    <AssemblyName>AdmissionAssistant.Core</AssemblyName>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
  </ItemGroup>

</Project>
