"""Live per-request progress for the STUDENT widget: GET /api/progress.

Why this exists separately from /admin/trace/stream
---------------------------------------------------
Both read the same hub, and that is exactly why this is its own module with
its own rules. The admin stream is a debugging tool: it carries the real
question text, the real answer, retrieved chunk snippets, prompt ids and
model names, for every request in the system, gated behind the admin token.
None of that may reach a student's browser. So this route does not filter the
admin payload, it CONSTRUCTS a new one - an allow-list of steps, mapped to
plain-language labels, carrying only counts and page numbers.

Anything the pipeline starts emitting later is therefore invisible here until
someone deliberately adds it, which is the right default for a surface a
student can open devtools on.

Two subscriptions, one trace
----------------------------
A student may only watch their OWN request. The trace id is generated by the
widget and sent with the question (see trace/events.py's TraceCollector), so
it is a 128-bit unguessable value the client already knows; events for any
other trace are dropped, and events for another project are dropped even if
the id somehow matched. That is what authorises the subscription - the API
key stays in a header on /api/chat rather than being pushed into a URL query
string where it would land in access logs and browser history, which is what
using EventSource here would have forced.

The race, and why the stream sends `ready` first
------------------------------------------------
The hub broadcasts live and stores nothing, so anything published before the
student subscribes is simply gone. If the widget fired the question and then
subscribed, it would routinely miss the first steps of exactly the fast
requests where those are the only steps. The route therefore emits a `ready`
frame as soon as it is subscribed, and the widget waits for it before asking
its question - one local round trip, in exchange for a stream that cannot
start halfway through.
"""

import json
import queue
import re

from ..storage import apikeys
from ..trace import hub

_TRACE_ID_RE = re.compile(r"\A[0-9a-f]{32}\Z")

# How long one progress stream may stay open. A student's request finishes in
# seconds; this only bounds an abandoned connection whose final_answer never
# arrived (a crashed request, a closed laptop lid), so the thread and its
# queue get reclaimed instead of living until the process restarts.
_MAX_SECONDS = 300

# Steps the student is allowed to see, in the order the pipeline runs them,
# each with the phrasing a 17-year-old would actually understand. "guard" and
# "cache_lookup" are deliberately absent: a guard firing is an internal
# routing decision, and telling a student their answer came from a cache
# invites "so is it out of date?" - a question the cache's own provenance
# checks already answer better than a progress row can.
_STEPS = {
    "routing":      "Understanding your question",
    "retrieval":    "Searching the prospectus",
    # Not "Reading the fee table": this step runs on every question and often
    # finds nothing, so naming a fee table told a student asking about
    # DOCUMENTS that their fees were being looked up.
    "table_lookup": "Checking the tables",
    "generation":   "Writing your answer",
    "validation":   "Double-checking the details",
    "final_answer": "Done",
}

# Per-step, the ONLY detail fields that may leave the server, and what each
# becomes on screen. Everything else in the event - question text, snippets,
# prompts, model names, scores - is dropped by omission rather than by a
# blocklist, so a new field added upstream is private until chosen otherwise.
_DETAIL = {
    "retrieval": lambda d: _pages(d),
    "generation": lambda d: None,
    "validation": lambda d: None,
}


def _pages(detail):
    """"4 sections, pages 5, 16, 18" - page numbers only.

    Safe to show because the widget already prints the same page references
    beside a finished answer; this just says so while the work is happening.
    """
    chunks = detail.get("chunks") or detail.get("results") or []
    pages = []
    for chunk in chunks:
        page = chunk.get("page") if isinstance(chunk, dict) else None
        if isinstance(page, int) and page not in pages:
            pages.append(page)
    if not pages:
        return None
    shown = sorted(pages)[:6]
    return f"{len(chunks)} sections, page{'s' if len(shown) > 1 else ''} " + \
           ", ".join(str(p) for p in shown)


def _send(self, payload):
    self.wfile.write(f"data: {json.dumps(payload)}\n\n".encode("utf-8"))
    self.wfile.flush()


def handle_progress(self):
    """SSE of one request's real pipeline steps, for the widget that asked it."""
    project_id = apikeys.resolve_active(self.headers.get("X-API-Key"))
    if not project_id:
        self._json(401, {"error": "Missing or inactive API key."})
        return

    trace_id = ""
    if "?" in self.path:
        for part in self.path.split("?", 1)[1].split("&"):
            if part.startswith("traceId="):
                trace_id = part[len("traceId="):]
    if not _TRACE_ID_RE.match(trace_id):
        self._json(400, {"error": "A 32-character hex traceId is required."})
        return

    q = hub.subscribe()
    try:
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "keep-alive")
        # This stream is per-request and short-lived; a proxy buffering it
        # would defeat the entire point by delivering every step at once,
        # after the answer has already rendered.
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()
        # Tells the widget it is safe to ask its question now - see module
        # docstring on the race this closes.
        _send(self, {"step": "ready"})

        waited = 0.0
        while waited < _MAX_SECONDS:
            try:
                event = q.get(timeout=15)
            except queue.Empty:
                waited += 15
                self.wfile.write(b": ping\n\n")
                self.wfile.flush()
                continue
            if event.get("traceId") != trace_id or event.get("projectId") != project_id:
                continue
            step = event.get("step")
            if step not in _STEPS:
                continue
            payload = {"step": step, "label": _STEPS[step], "seq": event.get("seq")}
            detail = (_DETAIL.get(step) or (lambda d: None))(event.get("detail") or {})
            if detail:
                payload["detail"] = detail
            _send(self, payload)
            if step == "final_answer":
                return
    except (BrokenPipeError, ConnectionAbortedError, ConnectionResetError):
        # The student navigated away or sent another question. Normal.
        return
    finally:
        hub.unsubscribe(q)
